<#
.SYNOPSIS
Selective uninstaller: removes claude-base sync artifacts from ~/.claude/
while preserving personal files. Designed for clean re-install when the
installer itself is updated.

.DESCRIPTION
Removes the exact set of files that came from the claude-base git repo:
  - ~/.claude/.git/                  (git working copy)
  - everything tracked by HEAD       (CLAUDE.md, agents/, skills/,
                                      memory/, scripts/, etc.)

Preserves -- never touched:
  - .credentials.json     (Anthropic login)
  - settings.local.json   (local permissions/env vars)
  - history.jsonl         (CLI command history)
  - file-history/         (file edit history)
  - backups/, cache/, downloads/
  - plugins/              (Claude Code plugins)
  - projects/             (auto-memory AND chat sessions -- the actual
                           .jsonl transcripts live in projects/<encoded-
                           cwd>/<uuid>.jsonl, scoped per working dir)
  - anything else NOT in claude-base HEAD (conservative -- prefer leaving
    a stranger over deleting something important)

Strategy:
  1. If ~/.claude/.git/ is a valid repo -- use 'git ls-tree -r HEAD'
     to get the exact list of files that came from claude-base.
  2. Otherwise -- fall back to a hard-coded list of known managed paths.

What this uninstaller NEVER touches (outside ~/.claude/):
  - VS Code                         (Stage 2 of Install)
  - Claude VS Code extension        (Stage 4)
  - Set-Proxy.ps1, ~/.claude-proxy.json
  - Node.js, Claude Code CLI binary
  - uv binaries
  - uvx cache (just unused MCP packages, takes a few minutes to redownload)
  - anything outside ~/.claude/

A full backup of ~/.claude/ is created at ~/.claude.uninstall-backup-<ts>
BEFORE any removal. Restore = remove ~/.claude/ and move backup back.

After uninstall: re-run Install.ps1. Apply-ClaudeMd will detect that
~/.claude/ exists but is not a git repo (CASE 4 -- migration), back up
again, preserve personal files, and clone a fresh claude-base over.

.PARAMETER Yes
Skip confirmation prompt -- for CI / non-interactive use.

.PARAMETER DryRun
Print the plan (what would be removed / preserved), but do NOT remove
anything. No backup is created either. Safe to run on a real system.

.PARAMETER ClaudeDir
Override the ~/.claude/ path -- for testing on a sandbox copy. Default:
$env:USERPROFILE\.claude

.NOTES
Idempotent: re-running on an already-uninstalled ~/.claude/ is a no-op
(prints "nothing to remove").

ASCII-only Write-Host messages to avoid Windows PowerShell 5.1 codepage
issues.

Symmetric with Apply-ClaudeMd.ps1 $PreservedItems list. If you change
one, change the other.
#>

[CmdletBinding()]
param(
    [switch]$Yes,
    [switch]$DryRun,
    [string]$ClaudeDir = (Join-Path $env:USERPROFILE '.claude')
)

$ErrorActionPreference = "Stop"

# Personal items that must survive (mirror of Apply-ClaudeMd $PreservedItems)
$PreservedItems = @(
    '.credentials.json',
    'settings.local.json',
    'history.jsonl',
    'file-history',
    'backups',
    'cache',
    'downloads',
    'plugins',
    'projects'
)

# Fallback list used only if .git is missing or ls-tree fails.
# Must include everything that lives in the claude-base repo root.
$FallbackManagedItems = @(
    '.git',
    '.gitignore',
    'CLAUDE.md',
    'README.md',
    'settings.json',
    'agents',
    'skills',
    'commands',
    'memory',
    'session-reports',
    'harvested',
    'scripts',
    'auto-sync.log'   # generated by hooks, not in repo, but tied to it
)

function Write-Step { param($m) Write-Host "  $m" -ForegroundColor Cyan }
function Write-OK   { param($m) Write-Host "  [OK] $m" -ForegroundColor Green }
function Write-Warn { param($m) Write-Host "  [WARN] $m" -ForegroundColor Yellow }
function Write-Err  { param($m) Write-Host "  [ERR] $m" -ForegroundColor Red }

Write-Host ""
Write-Host "=== Claude Code uninstaller (selective) ===" -ForegroundColor White
Write-Host "    Target: $ClaudeDir" -ForegroundColor Gray
Write-Host "    Removes: claude-base git artifacts (CLAUDE.md, agents/, skills/, .git/, ...)" -ForegroundColor Gray
Write-Host "    Preserves: credentials, history, plugins, projects, settings.local.json" -ForegroundColor Gray

if (-not (Test-Path $ClaudeDir)) {
    Write-Warn "$ClaudeDir does not exist. Nothing to uninstall."
    exit 0
}

# === Build list of items to remove ===
$itemsToRemove = @()
$strategy = ""

$gitDir = Join-Path $ClaudeDir '.git'
if (Test-Path $gitDir) {
    Push-Location $ClaudeDir
    try {
        # ls-tree HEAD -- gives exact set of files tracked by claude-base.
        # NO 2>&1 redirect (PS 5.1 wraps native stderr in NativeCommandError).
        $tracked = & git ls-tree -r HEAD --name-only
        $gitExit = $LASTEXITCODE
    } finally {
        Pop-Location
    }
    if ($gitExit -eq 0 -and $tracked) {
        $strategy = "git-aware (ls-tree HEAD)"
        $itemsToRemove = @($tracked)
        $itemsToRemove += '.git'
    } else {
        $strategy = "fallback list (.git present but ls-tree failed exit=$gitExit)"
        $itemsToRemove = $FallbackManagedItems
    }
} else {
    $strategy = "fallback list (.git missing)"
    $itemsToRemove = $FallbackManagedItems
}

# Filter: keep only items that actually exist and are NOT in preserved list.
# For nested paths from git ls-tree, the first segment determines preservation.
$itemsToRemove = $itemsToRemove | Where-Object {
    $rootSegment = $_.Split('/')[0]
    (Test-Path (Join-Path $ClaudeDir $_)) -and ($PreservedItems -notcontains $rootSegment)
} | Sort-Object -Unique

# Find present preserved items (for the plan output)
$presentPreserved = $PreservedItems | Where-Object {
    Test-Path (Join-Path $ClaudeDir $_)
}

# Find "unknown" items -- not in either list (will be preserved by default)
$rootRemovals = ($itemsToRemove | ForEach-Object { $_.Split('/')[0] }) | Sort-Object -Unique
$allRoots = Get-ChildItem $ClaudeDir -Force | Select-Object -ExpandProperty Name
$unknown = $allRoots | Where-Object {
    ($rootRemovals -notcontains $_) -and ($PreservedItems -notcontains $_)
}

# === Print plan ===
Write-Host ""
Write-Host "Plan (${strategy}):" -ForegroundColor Cyan

if ($itemsToRemove.Count -eq 0) {
    Write-Host "  Nothing to remove -- ${ClaudeDir} already clean of claude-base artifacts." -ForegroundColor Gray
    exit 0
}

Write-Host "  Will REMOVE ($($itemsToRemove.Count) items):" -ForegroundColor Yellow
foreach ($i in ($itemsToRemove | Select-Object -First 30)) {
    Write-Host "    - $i"
}
if ($itemsToRemove.Count -gt 30) {
    Write-Host "    ... and $($itemsToRemove.Count - 30) more"
}

Write-Host ""
Write-Host "  Will PRESERVE (personal):" -ForegroundColor Green
if ($presentPreserved) {
    foreach ($i in $presentPreserved) {
        Write-Host "    - $i"
        # Special: count chat .jsonl files in projects/ so the user sees
        # explicitly that chat history is NOT deleted.
        if ($i -eq 'projects') {
            $projDir = Join-Path $ClaudeDir 'projects'
            $jsonls = Get-ChildItem $projDir -Recurse -File -Force -ErrorAction SilentlyContinue |
                      Where-Object { $_.Extension -eq '.jsonl' }
            if ($jsonls) {
                $totalMb = [math]::Round(($jsonls | Measure-Object Length -Sum).Sum / 1MB, 1)
                Write-Host "        contains $($jsonls.Count) chat session(s), ~${totalMb} MB -- NOT deleted" -ForegroundColor Green
            }
        }
    }
} else {
    Write-Host "    (none of the preserved items are present)" -ForegroundColor Gray
}

if ($unknown) {
    Write-Host ""
    Write-Host "  Will PRESERVE (unknown -- not in either list, kept conservatively):" -ForegroundColor Green
    foreach ($i in $unknown) { Write-Host "    - $i" }
}

Write-Host ""
Write-Host "  NOT touched (outside ${ClaudeDir}):" -ForegroundColor Gray
Write-Host "    VS Code, Claude VS Code extension, Set-Proxy.ps1," -ForegroundColor Gray
Write-Host "    ~/.claude-proxy.json, Node.js, Claude CLI binary, uv, uvx cache" -ForegroundColor Gray
Write-Host ""

if ($DryRun) {
    Write-Host "  -DryRun: stopping here. No changes made, no backup created." -ForegroundColor Cyan
    exit 0
}

if (-not $Yes) {
    $resp = Read-Host "Proceed? (y/N)"
    if ($resp -ne 'y' -and $resp -ne 'Y') {
        Write-Warn "Cancelled by user."
        exit 0
    }
}

# === Execute ===

# 1. Full backup
$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$backupDir = "${ClaudeDir}.uninstall-backup-${timestamp}"
Write-Step "Backing up ${ClaudeDir} -> ${backupDir}..."
Copy-Item -Path $ClaudeDir -Destination $backupDir -Recurse -Force
Write-OK "Backup created."

# 2. Remove items (longest paths first -- removes files before their parent dirs)
$sortedItems = $itemsToRemove | Sort-Object -Property Length -Descending
foreach ($item in $sortedItems) {
    $path = Join-Path $ClaudeDir $item
    if (Test-Path $path) {
        Remove-Item -Path $path -Recurse -Force -ErrorAction SilentlyContinue
        Write-OK "removed: $item"
    }
}

# 3. Clean up empty directories left behind by file removals.
# Use -split (regex operator) for splitting on either path separator --
# .Split('\','/') would be parsed as Split(char, int) in PowerShell 5.1
# and try to cast '/' to int.
$pass = 0
do {
    $emptied = $false
    $pass++
    Get-ChildItem $ClaudeDir -Recurse -Directory -Force -ErrorAction SilentlyContinue |
        Where-Object { -not (Get-ChildItem $_.FullName -Force -ErrorAction SilentlyContinue) } |
        ForEach-Object {
            $relPath = $_.FullName.Substring($ClaudeDir.Length).TrimStart([char[]]@('\','/'))
            $rootSegment = ($relPath -split '[\\/]')[0]
            if ($PreservedItems -notcontains $rootSegment) {
                Remove-Item $_.FullName -Force -ErrorAction SilentlyContinue
                $emptied = $true
            }
        }
} while ($emptied -and $pass -lt 10)

# === Done ===
Write-Host ""
Write-OK "Uninstall complete."
Write-OK "Backup: $backupDir"
Write-Host "         (delete it manually after verifying everything is fine)" -ForegroundColor Gray
Write-Host ""

Write-Host "Remaining in ${ClaudeDir}:" -ForegroundColor Cyan
$remaining = Get-ChildItem $ClaudeDir -Force | Select-Object -ExpandProperty Name
if ($remaining) {
    foreach ($i in $remaining) { Write-Host "  - $i" -ForegroundColor White }
} else {
    Write-Host "  (empty)" -ForegroundColor Gray
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Re-run .\Install.ps1 for a fresh install." -ForegroundColor White
Write-Host "     Apply-ClaudeMd CASE 4 will preserve the files left here." -ForegroundColor White
Write-Host "  2. If something is wrong, restore from backup:" -ForegroundColor White
Write-Host "       Remove-Item ${ClaudeDir} -Recurse -Force" -ForegroundColor Gray
Write-Host "       Move-Item ${backupDir} ${ClaudeDir}" -ForegroundColor Gray
Write-Host ""
Write-Host "Notes about chat history after re-install:" -ForegroundColor Cyan
Write-Host "  - Chats live in projects/<encoded-cwd>/<uuid>.jsonl. They are" -ForegroundColor Gray
Write-Host "    preserved here AND in the backup, never deleted by Uninstall." -ForegroundColor Gray
Write-Host "  - Claude Code UI shows chats scoped by the cwd you open --" -ForegroundColor Gray
Write-Host "    if you open VS Code in a different folder, that folder's" -ForegroundColor Gray
Write-Host "    chats show up. This is by design, not lost history." -ForegroundColor Gray
Write-Host "  - After a fresh Install you may need to run 'claude /login'" -ForegroundColor Gray
Write-Host "    once -- credentials.json is preserved, but the auth token" -ForegroundColor Gray
Write-Host "    inside it may have expired during the migration window." -ForegroundColor Gray
Write-Host ""
